### ISSUE TITLE
Diagram Specific Theme breaks rendering

### ISSUE THREAD

**Issue by Lockszmith-GH** [silverbulletmd/silverbullet-mermaid#1]
First, thank you so much for making SilverBullet.md as well as this plug.

The Issue
--------------
While copying over a diagram I made, the rendering was broken, instead I got a view of source code.
SilverBullet Log View did not provide any insight, nether did the JavaScript console.

With some trial and error, I found that the `%%{init...}%%` directive for [Diagram Specific Theme](https://mermaid.js.org/config/theming.html#diagram-specific-themes) is the one that failed. Removing that line allowed the drawing to appear, but without the dark color scheme that I needed for dark-mode.

Hope this is something you can fix.

The Code I tried
-----------------------
```
sequenceDiagram
%%{init: {'theme':'dark'}}%%
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
    Alice-)John: See you later!
```

What I was expecting to see
-----------------------------------------
[![](https://mermaid.ink/img/pako:eNpNT8FqhDAU_JXsA5GCK6sxUXPYUii0FHraW_GS6msN1WQbI60V_73R7ULfad4wM8zMUJsGQcCAnyPqGu-VfLeyr3QQzEorJ8gcuhZ7DEXYSPsRLksQVJr4u-tUjfvj8cm0WpBH7DpDVhyR1nwRaZFMZry9aFd-77WbR5AHi9Lt_sfcXFJOuLlIJx3aHUTQo-2lanzDeZVXsJWpQHj4KgePKr14nRydOU26BuHsiBGM58ZH_K0B8Sa7wbPYKGfs82XytjyCs9QvxvRXo39BzPANIuFJzIqsoEXB86TIWQQTCJqyOOM0zxmnWc4ZXyL42fyHmNM0yUrKDoyxskzS5RfG7Wvh?type=png)](https://mermaid.live/edit#pako:eNpNT8FqhDAU_JXsA5GCK6sxUXPYUii0FHraW_GS6msN1WQbI60V_73R7ULfad4wM8zMUJsGQcCAnyPqGu-VfLeyr3QQzEorJ8gcuhZ7DEXYSPsRLksQVJr4u-tUjfvj8cm0WpBH7DpDVhyR1nwRaZFMZry9aFd-77WbR5AHi9Lt_sfcXFJOuLlIJx3aHUTQo-2lanzDeZVXsJWpQHj4KgePKr14nRydOU26BuHsiBGM58ZH_K0B8Sa7wbPYKGfs82XytjyCs9QvxvRXo39BzPANIuFJzIqsoEXB86TIWQQTCJqyOOM0zxmnWc4ZXyL42fyHmNM0yUrKDoyxskzS5RfG7Wvh)

**Comment by zefhemel** [comment]
I have practically 0 Mermaid knowledge and I'm seeing the same issue you see. However, when I removed the quotes around 'theme' the diagram did seem to load, albeit without actually showing up dark:

```mermaid
sequenceDiagram
%%{init: {theme:'dark'}}%%
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
    Alice-)John: See you later!
```

**Comment by Lockszmith-GH** [comment]
Thanks for looking into it.

I wonder if there is a 'trace' flag you can switch on with mermaid.
In anyway, if you can't tackle it at this point, I'll try at sometime in the future - just don't have the bandwidth right now, and luckily we know how to bypass it so it wont break for now.

I'm slow to adopt SilverBullet as it requires me to change some of my muscle-memory for note taking, but I love what you did with it, and will continue to follow your progress.

**Comment by ancho** [comment]
Turns out you have to use Frontmatter to configure stuff since 10.5.0 of mermaid.

See https://mermaid.js.org/config/configuration.html

```
---
config:
  theme: dark
---
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
    Alice-)John: See you later!
```

**Comment by DaniloMurer** [comment]
@ancho yeah that's exactly what's wrong. thanks for the answer, was starting to question myself ahahahaha. They don't mention that frontmatter anywhere in the theming docs [Mermaid theming](https://mermaid.js.org/config/theming.html)
