### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by nightscape** [silverbulletmd/silverbullet-mermaid#5]
Hi!
I'm not sure if this is some problem on my side, but when I try to create a Mermaid diagram I get the following error in the browser console:
```
Subresource Integrity: The resource 'https://cdn.jsdelivr.net/npm/mermaid@10.9.3/dist/mermaid.min.js' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.
```

[Stackoverflow says](https://stackoverflow.com/a/35323436/146625) that a `crossorigin="anonymous"` is required, which afaiu [should actually be added in `panel_html.ts`](https://github.com/silverbulletmd/silverbullet/blob/main/web/components/panel_html.ts#L98).

I can also see that the request is being served from cache:
![image](https://github.com/user-attachments/assets/59605bed-7856-42b2-96c3-38a2ee5ab194)

I'm a little bit at a loss here (more of a backend guy 😉 ).
I'm running SilverBullet from the up-to-date `main` branch (as of 2024-11-20, commit `51fc5952`).

**Comment by gorootde** [comment]
Just tried this in different browsers. Seems like in some browsers the property is case sensitive. The liked PR should fix this.
